### ISSUE TITLE
Simple Conteneur Docker avec Terraform

### ISSUE THREAD

**Issue by papicool** [wingufactory/lecloudfacile-devops-training#133]

**Comment by papicool** [comment]
@K6SY @julesyoum pour review

**Comment by K6SY** [comment]
@papicool  kudos for your work

I just switch this lab as the first one on the terraform topic: 04-terraform-execution-container.md

The 'getting started' lab will the last lab due to Cloud interaction (Cloud out-of the scope of the training)
