### ISSUE TITLE
La virtualisation applicative avec Docker

### ISSUE THREAD

**Issue by K6SY** [wingufactory/lecloudfacile-devops-training#19]
Architecture & concepts fondamentaux de Docker (Isolation, control groups, image, conteneur, cycle de vie des conteneurs, etc.)

**Comment by K6SY** [comment]
@julesyoum @papicool  for review.

docs/03-conteneurisation/01-virtualisation-applicative.md

**Comment by julesyoum** [comment]
Ok for me 👍🏽

**Comment by K6SY** [comment]
I will close the issue
