### ISSUE TITLE
Création d’image avec Dockerfile

### ISSUE THREAD

**Issue by K6SY** [wingufactory/lecloudfacile-devops-training#23]
Syntaxe, directives et best practices (analyse statique, build multi-stage, recommandations, etc.

**Comment by K6SY** [comment]
@julesyoum @papicool 

Can you reveiw the following content:

branch: features/03-conteneurisation
file: docs/03-conteneurisation/05-dockerfile.md.

**Comment by julesyoum** [comment]
Great work @K6SY 
I'm gonna close the issue.
