### ISSUE TITLE
Déploiement d’une base de données MySQL avec Docker

### ISSUE THREAD

**Issue by K6SY** [wingufactory/lecloudfacile-devops-training#29]

**Comment by K6SY** [comment]
@julesyoum @papicool  for reviews

**Comment by julesyoum** [comment]
Lab tested successfully ! Great work @K6SY !
Images was not displayed. i fixed it with this commit https://github.com/wingufactory/lecloudfacile-devops-training/commit/f673e8594ac836e24a721ca390e46962206e17c4

**Comment by K6SY** [comment]
@julesyoum 

Thanks for fixing. However, the first path was correct for mkdocs that need full path. When you use relative path, you can see image on github but none in mkdocs.

Anyway, we can keep this as is now and make the modification for mkdocs compatibility once all issue close.

I will close this one

**Comment by julesyoum** [comment]
merci pour l'info @K6SY.
