### ISSUE TITLE
Découverte de Git

### ISSUE THREAD

**Issue by K6SY** [wingufactory/lecloudfacile-devops-training#40]
Mécanismes de fonctionnement, Branching modèle, composant et commande de base

**Comment by julesyoum** [comment]
@K6SY , @papicool , @papemamadou91  Thanks for review !

**Comment by papemamadou91** [comment]
Great job !
i have just added the section about rollback changes on Git if you don't mind --> https://github.com/wingufactory/lecloudfacile-devops-training/commit/d1aa12863a422ff666e3cb52e19967fde9397c7d

**Comment by papicool** [comment]
Reviewed this section -> OK for me, changed the task's status to DONE
