### ISSUE TITLE
Installation & configuration de Jenkins sur Docker

### ISSUE THREAD

**Issue by K6SY** [wingufactory/lecloudfacile-devops-training#42]

**Comment by K6SY** [comment]
@julesyoum  @papicool  for review please

**Comment by julesyoum** [comment]
Hello @K6SY on the jenkins.conf file there is jenkins-dev.lecloudfacile.io at the server_name level. So we put jenkins-dev.lecloudfacile.io on line 124 instead of jenkins.lcf.io ? as well as on line 149 ?

**Comment by julesyoum** [comment]
On line 130, we try to execute a command on the `jenkins` container to retrieve the jenkins password, while the container_name is `jenkins-dev` in the docker-compose.yaml file

**Comment by julesyoum** [comment]
On the last task, the build fails with the error message: “Pull access denied for lecloudfacile/inbound-agent, repository does not exist or may require 'docker login': denied: requested access to the resource is denied”, the image is not public

**Comment by K6SY** [comment]
> unix://var/run/docker.sock

The image is public. You can access it without login on dockerhub https://hub.docker.com/r/lecloudfacile/jenkins-agent

**Comment by K6SY** [comment]
> in line 218, we should enter: `unix://var/run/docker.sock` instead of `\var\run\docker.socker`.

Fixed

**Comment by K6SY** [comment]
> Hello [@K6SY](https://github.com/K6SY), in the jenkins.conf file there is jenkins-dev.lecloudfacile.io at the server_name level. So we put jenkins-dev.lecloudfacile.io on line 124 instead of jenkins.lcf.io ? as well as on line 149 ?

I will keep jenkins.lecloudfacile.io instead. The appropriate modification is done

**Comment by K6SY** [comment]
@julesyoum  I will close this ticket after briging modifications to fix. We can re-reun the lab again before starting the course to be sure everything will be good
