### ISSUE TITLE
Introduction sur Linux

### ISSUE THREAD

**Issue by K6SY** [wingufactory/lecloudfacile-devops-training#5]
Commandes de base, éditeurs, gestion des ressources(RAM, CPU, Disque), troubleshooting, adressage, routage, filtrage packet.

**Comment by K6SY** [comment]
@julesyoum  good Job

I refactor in a standard way how command is presented before group them in some categories.

However, some usefl commands for DevOps are not listed: netstat, nslookup, traceroute, dig, nc, telnet, history, etc. We need also for some command to enrich options.

I keep the card open. Feel free to complete

**Comment by julesyoum** [comment]
Thanks @K6SY  for the feedback, Update done, please review !

**Comment by papemamadou91** [comment]
Hello 

For this section, just the title to change from "**HEAD**" to "**TAIL**" --> https://github.com/wingufactory/lecloudfacile-devops-training/blob/features/01-prerequis/docs/01-prerequis/02-Intruduction-sur-linux.md#head-1

Except this, everything else is good. Nice one !

**Comment by papemamadou91** [comment]
What do you think also about adding in "Bonus" the reverse search functionality on linux & MacBook (with CTRL+R), I use it often and it is very useful for productivity 

https://eitca.org/cybersecurity/eitc-is-lsa-linux-system-administration/advancing-in-linux-sysadmin-tasks/linux-bash-shortcuts/examination-review-linux-bash-shortcuts/how-can-you-perform-a-reverse-search-in-the-command-history-using-keyboard-shortcuts-in-the-linux-shell/

**Comment by K6SY** [comment]
@papemamadou91 you can add reverse search. By the way, I will close the ticket

**Comment by julesyoum** [comment]
> Hello
> 
> For this section, just the title to change from "**HEAD**" to "**TAIL**" --> https://github.com/wingufactory/lecloudfacile-devops-training/blob/features/01-prerequis/docs/01-prerequis/02-Intruduction-sur-linux.md#head-1
> 
> Except this, everything else is good. Nice one !

done
